# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m pip install -r requirements.txt
        sudo apt-get install -y xvfb
              
    - name: Lint with pylint
      run: |
        pylint maidiary.py --exit-zero

    - name: Test with coverage and pytest
      run: |
        
        echo ""
        echo ""
        echo "Running tests"
        echo ""
        coverage run -m pytest
        echo ""
        echo ""
        echo ""
        echo "Coverage report:"
        echo ""
        coverage report -m
        echo ""
        echo ""
        coverage html
        

    - name: Building app
      run: |
        python -m build

    - name: Docker Login
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: peppeblu/maidiary:latest

    - name: Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}

        
